### ISSUE TITLE
How should recent, but not featured blog posts show up?

### ISSUE THREAD

**Issue by rtyler** [scribd/scribd.github.io#17]
This popped into my mind, but if the next blog post that's authored is not "featured", how would a new reader discover it?

**Comment by kylegordy** [comment]
@rtyler I think you zeroed in on this in the other issue. The two components not built yet that I think will solve this is the recommendations module and the post index filters. The two of those should help users find interesting content (new or old) to read.

Here's older screenshots of each feature:

<img width="1440" alt="Screen Shot 2019-11-25 at 4 18 14 PM" src="https://user-images.githubusercontent.com/3318020/69592992-c5d0f080-0fc5-11ea-8b74-5139b02235ad.png">
   
---
     
<img width="1442" alt="Screen Shot 2019-11-25 at 4 17 46 PM" src="https://user-images.githubusercontent.com/3318020/69593031-ebf69080-0fc5-11ea-8f35-5523fca0be97.png">

**Comment by kylegordy** [comment]
@rtyler I think we can close this also now that recommendations and the post index filters are built.
