### ISSUE TITLE
Make the featured-series tags more permanent

### ISSUE THREAD

**Issue by rtyler** [scribd/scribd.github.io#19]
@kylegordy I was thinking about `featured-series` and I think to make a "related content" widget work long-term, we would be better served by having blog posts in a series share the same featured-series tag.

For example:

* `featured-weaver`
* `featured-aws-migration`

Then the hero on the home page could just be a config value stating which featured series to use, but the posts would be immutable, so the related content widget we discussed would always work.

Whatcha think?

**Comment by kylegordy** [comment]
@rtyler I think that would work well. That way the series groupings stay together as you mentioned. 

I'll try to get a related content module sorted out before Thanksgiving so we can play around it. I imagine this approach will make for better recommendations long-term

**Comment by kylegordy** [comment]
@rtyler I made featured series tags unique [a few days ago](https://github.com/scribd/scribd.github.io/commit/3b95d248cb24e0b0858ec52ea2952fef6acb9890). I think we can close this now 😄
