### ISSUE TITLE
Repo URL is missing a slash

### ISSUE THREAD

**Issue by kylegordy** [scribd/scribd.github.io#30]
I just noticed the repo URL is missing a slash and won't resolve. Unfortunately, I don't have the permissions to fix it.

<img width="999" alt="Screen Shot 2019-12-06 at 3 58 12 PM" src="https://user-images.githubusercontent.com/3318020/70356579-b3b34580-1842-11ea-8336-0eee0a513899.png">

**Comment by rtyler** [comment]
Ah, I see. I was wondering what the problem was there, and couldn't figure it out :smile_cat:
