### ISSUE TITLE
Team Structure Section

### ISSUE THREAD

**Issue by kylegordy** [scribd/scribd.github.io#32]
@rtyler Now that the MVP is launched, I wanted to circle back on the team section we removed due to time constraints. 

Here's the [original design](https://sketch.cloud/s/QyQrm/a/Epw3Pd), and here's the [updated accordion design](https://sketch.cloud/s/QyQrm/a/RrJaq2) we talked about. 

What I like about the accordion is it allows users to peak into teams they're curious about without wasting a lot of space. I also ordered each team in a top-down version of your org chart, so it has another layer of meaning.

Anyways, let me know what you think.

**Comment by rtyler** [comment]
The non-spatial design I think is most scalable and workable for us.

**Comment by kylegordy** [comment]
@rtyler Ok cool, sounds good. I'll get the team accordions built out asap.
